Repository Stocil/Auth, pull requests merged in 2025-02, with the labels that each got.

#1 Добавил роуты и UI для формы авторизации
  package-lock.json
  package.json
  src/App.tsx
  src/components/button/button-styles.ts
  src/components/button/button.tsx
  src/components/button/index.ts
  src/components/divider/divider.ts
  src/components/divider/index.ts
  src/components/google-login-button/google-login-button.tsx
  src/components/google-login-button/index.ts
  src/components/input/index.ts
  src/components/input/input-styles.ts
  src/components/input/input.tsx
  src/constants.ts
  src/features/page/index.ts
  src/features/page/page-styles.ts
  src/features/page/page.tsx
  src/main.tsx
  src/page/homepage/homepage.tsx
  src/page/homepage/index.ts
  src/page/login/index.ts
  src/page/login/login-header.tsx
  src/page/login/login-styled.ts
  src/page/login/login.tsx
  src/routes/index.tsx
  src/routes/routes-list.tsx
  src/routes/routes.tsx
Labels: feature

#2 Добавил стор и апи
  eslint.config.js
  package-lock.json
  package.json
  src/main.tsx
  src/page/login/login.tsx
  src/store/api/auth/auth.ts
  src/store/api/auth/index.ts
  src/store/api/constants.ts
  src/store/index.ts
  src/store/root-reducer.ts
  src/store/services/base-query.ts
  src/store/services/base.ts
  src/store/user/index.ts
  src/store/user/selectors.ts
  src/store/user/slice.ts
  src/store/user/types.ts
  src/types/entities/auth.ts
  src/types/index.ts
  src/utils/http-codes.ts
  tsconfig.app.json
Labels: feature

#4 Настроил преттиер, пофиксил абсолютные пути в проекте, отформатировал проект
  .prettierrc
  package-lock.json
  package.json
  src/components/button/button.tsx
  src/components/google-login-button/google-login-button.tsx
  src/components/input/input.tsx
  src/constants.ts
  src/constants/index.ts
  src/main.tsx
  src/pages/homepage/homepage.tsx
  src/pages/homepage/index.ts
  src/pages/login/index.ts
  src/pages/login/login-header.tsx
  src/pages/login/login-styled.ts
  src/pages/login/login.tsx
  src/routes/index.tsx
  src/routes/routes.tsx
  src/store/api/auth/auth.ts
  src/store/root-reducer.ts
  src/store/services/base-query.ts
  src/store/user/selectors.ts
  src/store/user/slice.ts
  src/store/user/types.ts
  src/theme/theme.tsx
  tsconfig.json
  vite.config.ts
Labels: refactor

#5 Реализовал отправку формы на BE при регистрации и входе
  src/components/input/input.tsx
  src/pages/login/hooks/index.ts
  src/pages/login/hooks/use-auth-user.ts
  src/pages/login/login.tsx
  src/pages/login/types.ts
  src/store/services/base-query.ts
Labels: feature

#6 добавил хедер
  src/components/app-bar/app-bar.tsx
  src/components/app-bar/index.ts
  src/features/page/page.tsx
Labels: feature

#8 Рефактор login страницы
  .prettierrc
  src/components/app-bar/app-bar.tsx
  src/hooks/use-logout.ts
  src/pages/authorization/authorization.tsx
  src/pages/authorization/hooks/index.ts
  src/pages/authorization/hooks/use-auth-user.ts
  src/pages/authorization/index.ts
  src/pages/authorization/login/index.ts
  src/pages/authorization/login/login-header.tsx
  src/pages/authorization/login/login-styled.ts
  src/pages/authorization/login/login.tsx
  src/pages/authorization/logout/index.ts
  src/pages/authorization/logout/logout-styles.ts
  src/pages/authorization/logout/logout.tsx
  src/pages/authorization/types.ts
  src/pages/layout/index.ts
  src/pages/layout/layout.tsx
  src/pages/layout/page-styles.ts
  src/pages/login/hooks/use-auth-user.ts
  src/pages/page/index.ts
  src/pages/page/page.tsx
  src/routes/routes-list.tsx
  src/routes/routes.tsx
  src/store/services/base-query.ts
  src/store/user/selectors.ts
  src/types/entities/auth.ts
Labels: refactor

#9 Добавил приватный роут
  src/components/input/input.tsx
  src/pages/authorization/hooks/use-auth-user.ts
  src/pages/authorization/login/login-styled.ts
  src/pages/authorization/login/login.tsx
  src/pages/homepage/homepage-styles.ts
  src/pages/homepage/homepage.tsx
  src/routes/private-route.tsx
  src/routes/routes.tsx
Labels: feature

#11 Настроил роуты для бека, добавил базовые хелперы для БД
  backend/package-lock.json
  backend/package.json
  backend/server.js
  backend/src/api/router.js
  backend/src/api/user/sign-up.js
  backend/src/data-base/data-base.js
  backend/src/data-base/helpers/addUser.js
  backend/src/server.js
Labels: feature, BE

#12 Внедрил тс
  backend/package-lock.json
  backend/package.json
  backend/src/api/router.ts
  backend/src/api/user/sign-up.ts
  backend/src/data-base/data-base.ts
  backend/src/data-base/helpers/addUser.ts
  backend/src/server.ts
  backend/src/types/users.ts
  backend/tsconfig.json
Labels: feature, BE

#13 Добавил в проект tsx, удалил ненужные зависимости и скрипты
  backend/package-lock.json
  backend/package.json
Labels: feature, BE

#14 Поправил пути, вынес в порты и ссылки в константы
  backend/src/api/routes.ts
  backend/src/api/user/sign-up.ts
  backend/src/constants/index.ts
  backend/src/data-base/data-base.ts
  backend/src/data-base/helpers/addUser.ts
  backend/src/data-base/index.ts
  backend/src/server.ts
Labels: refactor, BE

#17 Добавил валидацию access токена в access роуте
  backend/src/api/routes.ts
  backend/src/api/token/access.ts
  backend/src/api/user/sign-in.ts
  backend/src/api/user/sign-up.ts
  backend/src/constants/http-codes.ts
  backend/src/types/users.ts
  backend/src/utils/generate-tokens.ts
Labels: feature, BE

#18 Добавил рефреш роут
  backend/package-lock.json
  backend/package.json
  backend/src/api/routes.ts
  backend/src/api/token/access.ts
  backend/src/api/token/refresh.ts
  backend/src/constants/index.ts
  backend/src/server.ts
  backend/tsconfig.json
Labels: feature, BE

#19 Добавил мидлвару, которая проверяет на наличие валидного access токена в запросе
  backend/src/api/routes.ts
  backend/src/api/token/access.ts
  backend/src/api/user/sign-in.ts
  backend/src/constants/http-codes.ts
  backend/src/middleware/authenticate-token.ts
Labels: feature, BE

#20 Добавил dotenv, изменил все константы
  backend/.env
  backend/package-lock.json
  backend/package.json
  backend/src/constants/index.ts
  backend/src/server.ts
  backend/src/utils/generate-tokens.ts
Labels: feature, BE

#21 Перешел с локал сторейджа на куки
  frontend/src/components/google-login-button/google-login-button.tsx
  frontend/src/hooks/use-logout.ts
  frontend/src/store/services/base-query.ts
  frontend/src/utils/token.ts
Labels: feature, FE

#22 Разделил формы на отдельные компоненты
  frontend/src/components/google-login-button/google-login-button.tsx
  frontend/src/pages/authorization/login/login-footer.tsx
  frontend/src/pages/authorization/login/login-inputs.tsx
  frontend/src/pages/authorization/login/login-styled.ts
  frontend/src/pages/authorization/login/login.tsx
Labels: refactor, FE

#23 Пофиксил вход на BE, добавил access провайдер на FE
  backend/src/api/user/sign-in.ts
  backend/src/api/user/sign-up.ts
  backend/src/data-base/helpers/get-user-by-login.ts
  frontend/src/components/access-provider/access-provider.tsx
  frontend/src/components/access-provider/index.ts
  frontend/src/hooks/use-logout.ts
  frontend/src/main.tsx
  frontend/src/pages/authorization/hooks/use-auth-user.ts
  frontend/src/store/api/auth/auth.ts
  frontend/src/store/user/types.ts
  frontend/src/types/entities/auth.ts
  frontend/src/utils/token.ts
Labels: bug, feature, BE, FE

#24 Починил редирект в приватном роуте
  frontend/src/features/private-route/index.ts
  frontend/src/features/private-route/private-route.tsx
  frontend/src/routes/routes.tsx
Labels: bug, FE

#25 Добавил ручку /logout на BE, пофиксил access провайдер и приватный роут на FE
  backend/.env
  backend/src/api/routes.ts
  backend/src/api/token/delete.ts
  frontend/src/components/access-provider/access-provider.tsx
  frontend/src/features/private-route/private-route.tsx
  frontend/src/hooks/use-logout.ts
Labels: bug, feature, BE, FE

#26 Добавил реавторизацию, если access токен истек
  backend/.env
  backend/src/api/token/refresh.ts
  backend/src/api/user/sign-in.ts
  backend/src/api/user/sign-up.ts
  backend/src/middleware/authenticate-token.ts
  backend/src/server.ts
  backend/src/utils/generate-tokens.ts
  frontend/src/store/services/base-query.ts
Labels: feature, BE, FE

#27 Добавил снекбары
  backend/.env
  backend/src/api/token/delete.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/features/access-provider/access-provider.tsx
  frontend/src/features/access-provider/index.ts
  frontend/src/hooks/use-logout.ts
  frontend/src/hooks/use-snackbar.ts
  frontend/src/main.tsx
  frontend/src/pages/authorization/hooks/use-auth-user.ts
  frontend/src/store/api/auth/auth.ts
  frontend/src/types/index.ts
Labels: feature, BE, FE

#28 При регистрации обавил проверку на то, зарегистрирован ли пользователь с таким логином
  backend/src/api/user/sign-up.ts
  backend/src/constants/http-codes.ts
Labels: feature, BE

#29 Добавил react-hook-form
  backend/src/api/user/sign-in.ts
  backend/src/constants/http-codes.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/divider/divider.ts
  frontend/src/components/google-login-button/google-login-button.tsx
  frontend/src/components/input-field/index.ts
  frontend/src/components/input-field/input-field-styles.ts
  frontend/src/components/input-field/input-field.tsx
  frontend/src/pages/authorization/authorization.tsx
  frontend/src/pages/authorization/hooks/use-auth-user.ts
  frontend/src/pages/authorization/login/constants.ts
  frontend/src/pages/authorization/login/form/email-field.tsx
  frontend/src/pages/authorization/login/form/form.tsx
  frontend/src/pages/authorization/login/form/index.ts
  frontend/src/pages/authorization/login/form/login-field.tsx
  frontend/src/pages/authorization/login/form/password-field.tsx
  frontend/src/pages/authorization/login/form/repeat-password-field.tsx
  frontend/src/pages/authorization/login/login-footer.tsx
  frontend/src/pages/authorization/login/login-header.tsx
  frontend/src/pages/authorization/login/login-inputs.tsx
  frontend/src/pages/authorization/login/login-styled.ts
  frontend/src/pages/authorization/login/login.tsx
  frontend/src/pages/authorization/types.ts
  frontend/src/routes/routes.tsx
  frontend/src/utils/http-codes.ts
Labels: feature, FE

#30 Изменил цвета темы и зарестайлил некоторые компоненты
  backend/src/data-base/data-base.ts
  frontend/src/components/app-bar/app-bar-styles.ts
  frontend/src/components/app-bar/app-bar.tsx
  frontend/src/components/button/button-styles.ts
  frontend/src/pages/authorization/login/form/form.tsx
  frontend/src/pages/authorization/login/form/password-field.tsx
  frontend/src/pages/authorization/login/form/repeat-password-field.tsx
  frontend/src/pages/authorization/login/login-styled.ts
  frontend/src/pages/layout/layout.tsx
  frontend/src/theme/theme.tsx
Labels: FE

#31 Рефактор стора + добавил инфу пользователя в апп бар
  frontend/src/components/app-bar/app-bar-styles.ts
  frontend/src/components/app-bar/app-bar-user-info.tsx
  frontend/src/features/access-provider/access-provider.tsx
  frontend/src/pages/authorization/hooks/use-auth-user.ts
  frontend/src/pages/authorization/login/login.tsx
  frontend/src/pages/layout/layout-styles.ts
  frontend/src/pages/layout/layout.tsx
  frontend/src/pages/profile/index.ts
  frontend/src/pages/profile/profile.tsx
  frontend/src/routes/routes.tsx
  frontend/src/store/user/slice.ts
  frontend/src/store/user/types.ts
  frontend/src/types/entities/auth.ts
  frontend/src/utils/token.ts
Labels: feature, refactor, FE

#32 Добавил поле avatar на FE и BE
  backend/src/api/token/refresh.ts
  backend/src/api/user/sign-in.ts
  backend/src/api/user/sign-up.ts
  backend/src/data-base/data-base.ts
  backend/src/data-base/helpers/add-user.ts
  backend/src/types/users.ts
  frontend/src/components/app-bar/app-bar-user-info.tsx
  frontend/src/pages/layout/layout.tsx
  frontend/src/store/user/slice.ts
  frontend/src/store/user/types.ts
  frontend/src/types/index.ts
  frontend/src/utils/token.ts
Labels: feature, BE, FE

#33 Добавил page wrapper, добавил кастомный size к кнопке, добавил лодер к приватному роуту
  frontend/src/components/button/button-styles.ts
  frontend/src/components/button/button.tsx
  frontend/src/components/loader/index.ts
  frontend/src/components/loader/loader.tsx
  frontend/src/components/page-wrapper/index.ts
  frontend/src/components/page-wrapper/page-wrapper.tsx
  frontend/src/components/stack/index.ts
  frontend/src/components/stack/stack.ts
  frontend/src/features/private-route/private-route.tsx
  frontend/src/pages/profile/empty-page.tsx
  frontend/src/pages/profile/profile.tsx
Labels: feature, FE

#34 Добавил профиль пользователя
  frontend/src/components/app-bar/app-bar-styles.ts
  frontend/src/components/app-bar/app-bar-user-info.tsx
  frontend/src/features/private-route/private-route.tsx
  frontend/src/pages/profile/profile-styles.ts
  frontend/src/pages/profile/profile.tsx
  frontend/src/store/user/slice.ts
  frontend/src/store/user/types.ts
  frontend/src/theme/theme.tsx
Labels: feature, FE

#35 Добавил форму с инпутами в профиль
  frontend/src/components/input-field/input-field.tsx
  frontend/src/pages/profile/form/avatar-field.tsx
  frontend/src/pages/profile/form/email-field.tsx
  frontend/src/pages/profile/form/form.tsx
  frontend/src/pages/profile/form/index.ts
  frontend/src/pages/profile/form/login-field.tsx
  frontend/src/pages/profile/form/type.ts
  frontend/src/pages/profile/profile-styles.ts
  frontend/src/pages/profile/profile.tsx
Labels: feature, FE

#36 Добавил поле id на BE и FE, изменил типы для BE
  backend/src/api/token/refresh.ts
  backend/src/api/user/edit.ts
  backend/src/api/user/sign-in.ts
  backend/src/api/user/sign-up.ts
  backend/src/constants/http-codes.ts
  backend/src/data-base/data-base.ts
  backend/src/data-base/helpers/add-user.ts
  backend/src/data-base/helpers/get-user-by-id.ts
  backend/src/data-base/helpers/get-user-by-login.ts
  backend/src/data-base/helpers/update-user.ts
  backend/src/types/users.ts
  backend/src/utils/generate-tokens.ts
  frontend/src/pages/profile/form/form.tsx
  frontend/src/store/user/slice.ts
  frontend/src/store/user/types.ts
  frontend/src/utils/token.ts
Labels: feature, refactor, BE, FE
